global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'user-api'
    static_configs:
      - targets: ['user-api-container:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'product-api'
    static_configs:
      - targets: ['product-api-container:8001']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'order-api'
    static_configs:
      - targets: ['order-api-container:8002']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'payment-api'
    static_configs:
      - targets: ['payment-api-container:8003']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'mongodb'
    static_configs:
      - targets: ['mongodb-container:27017']
    scrape_interval: 30s
